### PR TITLE
Translation issues.

### LINKED ISSUE #441: Emulator does not read rom
### Expected behavior
Open the game when you select the rom

### Actual behavior
It says that it is not possible to read the rom, even if it is in the format .gba, .gbc or .gb and neither the place where it is

### Steps to reproduce the behavior
Open the emulator and select a rom

### ROM details
All GBA, GBC and GB games in any format

### Build details
Windows 8

Version 2.1.3

Edit:
This occurs in the default language (I do not know if translating yet the error occurred because I could not translate)

It seems that the bug happens after you change version

In version 1.8.0 and 2.1.0, I selected a folder, now in 2.1.3 it does not read the folder any more, only if it changes the game or the folder of the place

Sem título

Sem título 1

### PR DESCRIPTION
**Pull request by denisfa**
@rkitover  I had to fix some spelling for the french translation and create a function to initialize the regex properly. If we try like was before, the regex compiles the english words (don't use gettext to translate it). This is why the configuration was not set.

I have to update the transifex too, but first want your feedback regarding this. I suggest we drop all translation for buttons/axes/joy and use the english text only. The labels will remain translated, but these may cause a minor inconvenience when switching languages, as the app will complain about weird strings (set as french, then use en_US ==> warning about wrong configuration).

Fix #441, #437 and #273. I tested for french, german and portuguese. Everything worked as expected.

After your feedback I will update transifex accordingly. Then we can merge this.

### CODE REVIEW

**Comment by rkitover** [comment]
I don't think we should depend in any way on a translation being correct.

The question is, where is the correct translated string coming from if there is a mismatch, the code should simply use whatever the translation is.

**Comment by denisfa** [comment]
> I don't think we should depend in any way on a translation being correct.
> The question is, where is the correct translated string coming from if there is a mismatch, the code should simply use whatever the translation is.

The current translation is split on components. For example, with `fr_FR.utf8`, `Joy` goes to `Manette` but `Joy[0-9]+` stays with `Joy[0-9]+` instead of `Manette[0-9]+`. This is what I am calling spelling error. There are some minor ones when abbreviating directions. Check what was done on the `po` files.

**Comment by rkitover** [comment]
I understand, in this case we should simply have only one string being translated and that is what the regexes should be compiled with.

There should be no changes to the `.po` files.

**Comment by rkitover** [comment]
BTW I think I fixed the translation issues for the keyboard side in 30b92724.

**Comment by rkitover** [comment]
What is mean is, instead of translating both the strings `Joy` and `Joy[0-9]+` just translate the string `Joy` and concatenate it with whatever is necessary.

In this way the code will not depend on any parts of the translation.

**Comment by denisfa** [comment]
> BTW I think I fixed the translation issues for the keyboard side in 30b9272.

What was the issue? For translated keys?

> What is mean is, instead of translating both the strings Joy and Joy[0-9]+ just translate the string Joy and concatenate it with whatever is necessary.

Do you think it is necessary to translate the buttons and joystick binds? If we work with english only, we would not need to update/create translations for these. The labels and descriptions I would keep the way it is now. There is a possible issue that if you set these with a language, and then open vbam using another one, the user would lose all its input because they would not be recognized (with a warning message).

**Comment by rkitover** [comment]
Yes I think it doesn't hurt, see how in `keyedit.cpp` we use both e.g. `_("CTRL")` and `wxT("CTRL")`, we can do the same here.

In the regex, compile it as e.g.:

```
"(Joy|" + _("Joy") + ")"
```

adjust the match group number. Since `wxRegex` is POSIX regex it doesn't have non-capturing parens.

But the key issue is that only one translated string be used, we do not want to depend on the translation files in any way.

**Comment by denisfa** [comment]
> But the key issue is that only one translated string be used, we do not want to depend on the translation files in any way.

What do you mean? We don't depend on translation for it to work, but the strings that are not translated yet will keep the original text (english). This does not affect us. Unless you mean to show the translated text, if possible, and use all english under the hood. When the config is read, it will be translated to whatever language is set; likewise, when the config is saved, it will be with english text.

**Comment by rkitover** [comment]
Like I said, you are translating the whole regex when you should just translate the string "Joy". See above.

**Comment by denisfa** [comment]
> Like I said, you are translating the whole regex when you should just translate the string "Joy". See above.

Sorry, my head is all over the places now. I understand what you are doing here, but I did not give one information of mine. If we check the po files, we actually do not have the strings `Axis`, `Joy` and friends. For instance,

```
$ fgrep -RnwI ./po -e "Axis" -A 1
...
./po/wxvbam/tr.po:1131:msgid "Axis%d+"
./po/wxvbam/tr.po-1132-msgstr "Eksen%d+"
--
./po/wxvbam/tr.po:1136:msgid "Axis%d-"
./po/wxvbam/tr.po-1137-msgstr "Eksen%d-"
--
./po/wxvbam/tr.po:1189:msgid "Axis([0-9]+)([+-])"
./po/wxvbam/tr.po-1190-msgstr "Eksen([0-9]+)([+-])"
...
```
```
$ fgrep -RnwI ./po -e "Joy" -A 1
...
./po/wxvbam/pt_BR.po:1130:msgid "Joy%d-"
./po/wxvbam/pt_BR.po-1131-msgstr "Controle%d-"
--
./po/wxvbam/pt_BR.po:1189:msgid "^Joy([0-9]+)[-+]"
./po/wxvbam/pt_BR.po-1190-msgstr "^Controle([0-9]+)[-+]"
...
``` 

We only have the regex translation. This is why I did not want to do this split, and offered the idea of english only for these. If we are going to do something, we have to decide what we should do with the translation.

As far as I can tell, we can either:
1. stick with the current solution minus the po editing (that should be done on transifex);
2. only show the translated strings, but use english under the hood;
3. remove the regex from all po files (transifex), and replace them with the single keywords, then use your idea about setting up the regex to be english + current locale;
4. double the regex on `CompileRegex`, the same way you are suggesting to do for 3, eg
 `"(Joy%d-|" + _("Joy%d-") + ")"` etc.

I believe all of these are viable, given enough time to do it.  `1`, `3` and `4` have this hypothetical problem that if the user saves it Input on one language, then tries to run with other, he will be given a warning and its Input will be emptied. Very like what is happening with the stable version + warnings.

Hope I made more clear now why this is taking so long to close.

**Comment by rkitover** [comment]
I'm fine with just using english for this and not using the translated strings anymore.

**Comment by denisfa** [comment]
@rkitover That should be it. Every time I look at this I feel a bit of wasted potential, but it is true that this should allow us to focus on other stuff.

**Comment by rkitover** [comment]
We cannot remove the translation from keyboard keys, wx translates them unconditionally.

**Comment by rkitover** [comment]
Rebase your work into one commit that just removes the translation from joystick keys and don't do anything else.

**Comment by rkitover** [comment]
Also I fixed all the translation issues with the keyboard keys anyway.

**Comment by rkitover** [comment]
If you do want to translate the joystick strings, just use the actual word concatenated with other characters, once the string is pushed to transifex someone will translate it again.

**Comment by denisfa** [comment]
> We cannot remove the translation from keyboard keys, wx translates them unconditionally.

We can use `ToRawString()` to get the non-translated one. It is on the trick that you did to change the key into an accelerator to get the string.

> Rebase your work into one commit that just removes the translation from joystick keys and don't do anything else.

No problem, before I finish this I will check the translations on transifex. It is for me to remember.

> If you do want to translate the joystick strings, just use the actual word concatenated with other characters, once the string is pushed to transifex someone will translate it again.

The thing is here is that I do believe there are some good ideas about how to tackle this and I would not like to waste anything that we already have. But it is not up to me to decide this, and your solution is good enough for me. I will go with removing the translation of joystick keys. By next push here it will be done.

> Also I fixed all the translation issues with the keyboard keys anyway.

What issue? The keyboard being translated at the moment is also saved translated on `vbam.ini`. It works for that locale only. If it is not translated, then english text is used, so no actual issues minus partial translation.

**Comment by rkitover** [comment]
> What issue? The keyboard being translated at the moment is also saved translated on vbam.ini. It works
> for that locale only. If it is not translated, then english text is used, so no actual issues minus partial
> translation.

There were issues with this years ago for users of translations, I don't remember anymore, but I'm pretty sure I fixed them with 30b92724 and d585a610.

Once we merge this, we can do a new release, I will post instructions for you on the CHAT page for how to do the release.

**Comment by denisfa** [comment]
@rkitover Done. I still believe we are going to go back to this, since someone will complain that the joystick is not translated like the keys, but for now it should work.

**Pull request merged**
