### PR TITLE
Fix compilation warnings for MacOS build.

### PR DESCRIPTION
**Pull request by denisfa**
@rkitover The work we needed to do after #396. I need some checks here.

Some of these files do not include any headers except local ones. That is the reason why I copy & paste the solution for many files. I know there were memory leaks issues, but they came after compilation warnings so I think we can put these two together here.

### CODE REVIEW

**Comment by retro-wertz** [comment]
i would take out register keyword entirely

**Comment by rkitover** [comment]
> i would take out register keyword entirely

I'm fine with either solution.

@denisfa I can merge this if you are ready.

**Comment by denisfa** [comment]
I made some checks and it seems that this `register` qualifier is only actually used by old compilers... I also like the idea of removing this code rather than adding. If we can agree on this (use newer compilers), I will do a cleanup here.

**Comment by rkitover** [comment]
It will still work fine on older compilers without it, feel free to remove it.

**Comment by denisfa** [comment]
Alright, now it is done @rkitover.

**Comment by denisfa** [comment]
> If I may give you some more annoying advice, you should start learning the art of proper git commit messages

No problem, I will be working on writing better commit messages from now on.

**Pull request merged**
