### PR TITLE
Addressing audio plugin crash

### PR DESCRIPTION
**Pull request by briansrls**
Stereo buffer is not remade in the case of audio plugin
switch (only affects GBA, not GB).  This results in a crash.
We need to remake the stereo buffer and reinit the pointers
in Gba_Pcm.output or they will be dangling, and lead to a
crash.  Also, cleaning up the Multi_Buffer class a bit.

### CODE REVIEW

**Comment by negativeExponent** [comment]
soundReset() is suppose to be called after soundInit(). dunno how the standalone plugins are loaded, but if its calling soundInit, then its missing soundReset then.

this should work as well though, other than duplicated func calls.

**Comment by briansrls** [comment]
> soundReset() is suppose to be called after soundInit(). dunno how the standalone plugins are loaded, but if its calling soundInit, then its missing soundReset then.
> 
> this should work as well though, other than duplicated func calls.

The relevant code is at cmdevents.cpp:2689, it's calling soundInit without calling soundReset.  Is it safer to put a call to soundReset within soundInit, assuming there is no reason to call soundInit without soundReset?

**Comment by rkitover** [comment]
@briansrls 

I think this is fine, especially since you only call the function if the buffer does not exist.

`soundReset()` does other things which we may not always want.

And not having memory errors regardless of the API call sequence is a positive IMHO.

Are you ready for this to be merged?

Please ignore the appveyor failure, there is an issue with it right now.

**Comment by briansrls** [comment]
@rkitover yes, please merge it when you can.  Thanks

**Comment by negativeExponent** [comment]
a full init without the reset? ok fine. no further comment. more band-aid fixes

**Comment by briansrls** [comment]
#713

**Comment by rkitover** [comment]
@briansrls if you want the automatic commit -> issue closing behavior, you have to put a line like this in your commit message next time:

```
- Fix #713.
```

**Comment by briansrls** [comment]
Thanks, I'll try it next time

**Pull request merged**
