### PR TITLE
Fix automatic dynamic frame skipping

### PR DESCRIPTION
**Pull request by Steelskin**
The previously used algorithm was too aggressive. This fixes the issue by using the last second data and using a more gentle adjustment curve to prevent huge changes in frame skipping.

### CODE REVIEW

**Comment by Felipefpl** [comment]
I was having a weird situation playing golden sun with the hq2x filter where the FPS would go above the limit of 60, does this fix it?

**Comment by Steelskin** [comment]
> I was having a weird situation playing golden sun with the hq2x filter where the FPS would go above the limit of 60, does this fix it?

I doubt it. The only way to activate this code is by manually setting the frameskip value to -1 in the INI file.

**Comment by Felipefpl** [comment]
I see, thanks for the info.

**Comment by Squall-Leonhart** [comment]
there is an auto frameskip option in the menus that isn't hooked up i guess.

**Pull request merged**
