### PR TITLE
Libretro: Update GBC memory map and add core option sublabels

### PR DESCRIPTION
**Pull request by retro-wertz**

### CODE REVIEW

**Comment by denisfa** [comment]
@retro-wertz What is this for? Was there some issue related to this?

**Comment by retro-wertz** [comment]
are we sending PR only with issues now?

**Comment by denisfa** [comment]
> are we sending PR only with issues now?

> are we sending PR only with issues now? since when was my PR in question?

@retro-wertz Are you upset, pal? I am going to keep your message before you keep editing it from now on.

I asked what is this for so I can, at least, try to understand the need/reason behind it. No need to feel offended. I just want to know what this is for, so I can learn something from your brief commits.

Not my fault you only read `Was there some issue related to this?` instead of the my entire message.

**Comment by retro-wertz** [comment]
ill just start pushing to libretro from now then. have someone remove my credentials.

**Comment by orbea** [comment]
@denisfa This was useful, libretro allows core options to be documented in the frontend now.

@retro-wertz Please reconsider, I really appreciate the time spent working on this repo.

**Comment by denisfa** [comment]
@orbea Why can't he just say that, then? Look at this conversation... No idea why he gets so upset over this...

**Comment by ZachBacon** [comment]
@retro-wertz Please, tell me what's going on? Did some of us do something to offend you? I wish you'd let me know because it's never my wish to offend someone. If need be you can discuss with me in private either on IRC or on discord

**Pull request closed without merging**
