### PR TITLE
GBA bios improvement.

### PR DESCRIPTION
**Pull request by denisfa**
This should solve #695, at least that was the result from my testing.

### CODE REVIEW

**Comment by rkitover** [comment]
Very nice, can you please give me some info about how you did this, I would like to get involved in emulator accuracy fixes as well.

**Comment by rkitover** [comment]
Also when you can add the `- Fix #XXX` line to your commit messages, then we get the commit -> issue fix metadata.

**Comment by denisfa** [comment]
Try to start doing an emulator from zero and whatever you have to code or is learning, check the equivalent on this repo. See if you can identify something useful or already on our issues section. 

> Also when you can add the - Fix #XXX line to your commit messages, then we get the commit -> issue fix metadata.

These are random core improvements. They just happen to solve the issue. We might want to keep track of these for future references (and not closing the issue, at least for now).

**Comment by rkitover** [comment]
Yeah I was going to look at some emulation issues, I was wondering mainly what you are using for hardware reference, emulator accuracy checking etc..

**Comment by denisfa** [comment]
@rkitover Sorry for the delay, I have been really busy. That depends on where you can start. There are a couple of test GB/GBC ROMs out there, mainly [blargg](https://github.com/retrio/gb-test-roms.git), [mooneye-gb](https://github.com/Gekkio/mooneye-gb.git).

For GBA, there is the [mgba test suite](https://github.com/mgba-emu/suite). As far as docs go, I am trying to code my own emulator to learn the basics. In this case I am also learning ADA, but there are alternatives for other languages. If you want something more specific, I can link you what I saw/used at some point.

**Comment by rkitover** [comment]
@denisfa I just had an idea, could we use the mgba test suite or some such to run a bunch of emulator tests on travis as a rom, and have it generate some kind of signal that can be returned to the test harness to indicate the pass/fail state.

**Pull request merged**
