### PR TITLE
Introduce wxUserInput class

### PR DESCRIPTION
**Pull request by Steelskin**
This introduces a new abstraction for any user input. The long-term goal
is to replace every usage of "custom" {key, mod, joy} triplets in the
code base with this new class.

This class implements comparison operators, allowing for faster access
in a set or as a key in a map, compared to the vectors currently used.

Issue: #745

### CODE REVIEW

**Comment by Steelskin** [comment]
After that, it's mostly a matter of converting every usage of joy, key, mod and every call site.

**Comment by rkitover** [comment]
@Steelskin not really in a condition to read this stuff right now, if there are no functionality changes I'll trust your judgement on this.

**Comment by Steelskin** [comment]
The devil is in the details but the only functional change is that the global `keys_pressed` vector has been replaced with a set. This should be a bit faster and functionality should otherwise be identical. I tested a few things (different controllers, keyboard bindings. ...) to ensure there are no regressions.

**Comment by rkitover** [comment]
Awesome, thank you.

**Pull request merged**
