### PR TITLE
Update en.po

### PR DESCRIPTION
**Pull request by LordMagnum**
line corrections

### CODE REVIEW

**Comment by ZachBacon** [comment]
Translation updates should be sent to https://www.transifex.com/bgk/vba-m/

**Comment by rkitover** [comment]
It seems `en.po` was not managed by transifex, I am deleting it because there is already an `en_US.po`, `en_GB.po` and `en_BR.po`.

**Comment by LordMagnum** [comment]
Sorry foe this Question, but wat is en_BR <-- ? Me one will German de_DE Translate ^^

**Comment by rkitover** [comment]
I have no idea, I'm guessing it's some kind of brazillian dialect of english.

**Pull request closed without merging**
