### PR TITLE
Add back joystick polling while processing GUI event.

### PR DESCRIPTION
**Pull request by briansrls**
Also, add define for num joypads instead of magic number

### CODE REVIEW

**Comment by briansrls** [comment]
Fixes #711

**Comment by rkitover** [comment]
@denisfa we may have broken this in the input refactor, can you work with him on this.

@briansrls also you have to delete objects created with new, otherwise you have a memory leak. But more importantly, we already have a `JoystickPoller` running for the main app, because since the input refactor denisfa did we support joystick events for accelerators.

**Comment by rkitover** [comment]
@denisfa the issue here may be that with a game loaded, the poller is off, but with the config dialog open, the OnIdle calls to poll aren't running either.

**Comment by briansrls** [comment]
> @denisfa we may have broken this in the input refactor, can you work with him on this.
> 
> @briansrls also you have to delete objects created with new, otherwise you have a memory leak. But more importantly, we already have a `JoystickPoller` running for the main app, because since the input refactor denisfa did we support joystick events for accelerators.

@rkitover you're right, that was a silly mistake.  I can fix the memory leak, but from reading your comment I understand that there may be a more appropriate solution.  I don't understand the infrastructure of this program well enough to know, but I hope this PR highlights something important that has changed.

**Comment by briansrls** [comment]
Hi @rkitover, I looked into what you suggested, here is the behavior I'm seeing:

OnIdle is called while no game is running, both without the config dialogue open and with it open.
OnIdle is called while the game is running, unless the config dialogue is open.  For some reason the calls stop when config dialogue is opened.

I'm trying to figure out why now.

**Comment by rkitover** [comment]
Well the dialogs are modal, which means they are supposed to stop processing in other windows of the app, the first scenario you describe is strange.

**Comment by briansrls** [comment]
> Well the dialogs are modal, which means they are supposed to stop processing in other windows of the app, the first scenario you describe is strange.

I was able to confirm this behavior via gdb and also logging.  I thought the first scenario was correct, because don't we have OnIdle calls to a poller?  Right now config via joystick is working when a game isn't running. and I think it's working because of the OnIdle polling calls.  If we need to disallow OnIdle calls while the dialogue is open, it sounds like we need a new place for the joystick polling for input config.  Does that sound right?

**Comment by rkitover** [comment]
The timer runs when a game isn't loaded, I'm going to fix this now anyway.

**Pull request closed without merging**
